<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ALL_DRUG_CODE [
<!ELEMENT ALL_DRUG_CODE (DRUG)+>
<!ELEMENT DRUG (PROPRIETARY_NAME,NDC_PACKAGE_CODE,STRENGTH,DOSAGE_INFO,LABELER_NAME,NON_PROPRIETARY_NAME,SUBSTANCE_NAME,PRODUCT_TYPE_NAME,PACKAGE_DESC,CERTIFIED_THROUGH)>
<!ATTLIST DRUG CATEGORY CDATA #REQUIRED>
<!ELEMENT PROPRIETARY_NAME (#PCDATA)>
<!ELEMENT NDC_PACKAGE_CODE (#PCDATA)>
<!ELEMENT STRENGTH (#PCDATA)>
<!ELEMENT DOSAGE_INFO EMPTY>
<!ATTLIST DOSAGE_INFO type (TABLET|LOTION|LIQUID) #REQUIRED>
<!ATTLIST DOSAGE_INFO form (EFFERVESCENT|CHEWABLE|CAPSULE|LIQUID|LOTION|NA) #REQUIRED>
<!ATTLIST DOSAGE_INFO route (ORAL|OPHTHALMIC|TOPICAL) #REQUIRED>
<!ELEMENT LABELER_NAME (#PCDATA)>
<!ELEMENT NON_PROPRIETARY_NAME (#PCDATA)>
<!ELEMENT SUBSTANCE_NAME (#PCDATA)>
<!ELEMENT PRODUCT_TYPE_NAME EMPTY>
<!ATTLIST PRODUCT_TYPE_NAME type (OTC|PRESCRIPTION) #REQUIRED>
<!ELEMENT PACKAGE_DESC (#PCDATA)>
<!ELEMENT CERTIFIED_THROUGH (#PCDATA)>
]>
<ALL_DRUG_CODE>
  <DRUG CATEGORY="HEARTBURN">
    <PROPRIETARY_NAME>Alka-Seltzer Heartburn</PROPRIETARY_NAME>
    <NDC_PACKAGE_CODE>0280-0047-36</NDC_PACKAGE_CODE>
    <STRENGTH>1000 mg/1,1940  mg/1</STRENGTH>
    <DOSAGE_INFO type="TABLET" form="EFFERVESCENT" route="ORAL"></DOSAGE_INFO>
    <LABELER_NAME>Bayer HealthCare LLC.</LABELER_NAME>
    <NON_PROPRIETARY_NAME>Anhydrous citric acid, Sodium bicarbonate (heat-treated)</NON_PROPRIETARY_NAME>
    <SUBSTANCE_NAME>CITRIC ACID MONOHYDRATE;SODIUM BICARBONATE</SUBSTANCE_NAME>
    <PRODUCT_TYPE_NAME type = "OTC"></PRODUCT_TYPE_NAME>
    <PACKAGE_DESC>18 POUCH in 1 CARTON (0280-0047-36);2 TABLET, EFFERVESCENT in 1 POUCH</PACKAGE_DESC>
    <CERTIFIED_THROUGH>12/31/2019</CERTIFIED_THROUGH>
  </DRUG>
  <DRUG CATEGORY="HEARTBURN">
    <PROPRIETARY_NAME>CVS Health Extra Strength Heartburn Relief Antacid</PROPRIETARY_NAME>
    <NDC_PACKAGE_CODE>59779-880-78</NDC_PACKAGE_CODE>
    <STRENGTH>160 mg/1,105mg/1</STRENGTH>
    <DOSAGE_INFO type="TABLET" form="CHEWABLE" route="ORAL"></DOSAGE_INFO>
    <LABELER_NAME>CVS Pharmacy,Inc.</LABELER_NAME>
    <NON_PROPRIETARY_NAME>aluminum hydroxide and magnesium carbonate</NON_PROPRIETARY_NAME>
    <SUBSTANCE_NAME>ALUMINUM HYDROXIDE;  MAGNESIUM CARBONATE</SUBSTANCE_NAME>
    <PRODUCT_TYPE_NAME type = "OTC"></PRODUCT_TYPE_NAME>
    <PACKAGE_DESC>100 TABLET, CHEWABLE in 1 BOTTLE (59779-880-78)</PACKAGE_DESC>
    <CERTIFIED_THROUGH>12/31/2020</CERTIFIED_THROUGH>
  </DRUG>
  <DRUG CATEGORY="ECZEMA">
    <PROPRIETARY_NAME>Aveeno Active Naturals Eczema Therapy Moisturizing</PROPRIETARY_NAME>
    <NDC_PACKAGE_CODE>69968-0377-1</NDC_PACKAGE_CODE>
    <STRENGTH>10 mg/mL</STRENGTH>
	<DOSAGE_INFO type="LOTION" form="NA" route="TOPICAL"></DOSAGE_INFO>
    <LABELER_NAME>Johnson and Johnson Consumer Inc.</LABELER_NAME>
    <NON_PROPRIETARY_NAME>Oatmeal</NON_PROPRIETARY_NAME>
    <SUBSTANCE_NAME>OATMEAL</SUBSTANCE_NAME>
    <PRODUCT_TYPE_NAME type = "OTC"></PRODUCT_TYPE_NAME>
    <PACKAGE_DESC>354 mL in 1 BOTTLE, PUMP (69968-0377-1)</PACKAGE_DESC>
    <CERTIFIED_THROUGH>12/31/2019</CERTIFIED_THROUGH>
  </DRUG>
  <DRUG CATEGORY="ECZEMA">
    <PROPRIETARY_NAME>Cetaphil PRO Eczema Soothing Moisturizer</PROPRIETARY_NAME>
    <NDC_PACKAGE_CODE>0299-4130-01</NDC_PACKAGE_CODE>
    <STRENGTH>1 g/100mL</STRENGTH>
	<DOSAGE_INFO type="LOTION" form="NA" route="TOPICAL"></DOSAGE_INFO>
    <LABELER_NAME>Galderma Laboratories, L.P.</LABELER_NAME>
    <NON_PROPRIETARY_NAME>colloidal oatmeal</NON_PROPRIETARY_NAME>
    <SUBSTANCE_NAME>OATMEAL</SUBSTANCE_NAME>
    <PRODUCT_TYPE_NAME type = "OTC"></PRODUCT_TYPE_NAME>
    <PACKAGE_DESC>1 mL in 1 BOTTLE (0299-4130-01)</PACKAGE_DESC>
    <CERTIFIED_THROUGH>12/31/2020</CERTIFIED_THROUGH>
  </DRUG>
  <DRUG CATEGORY="REDEYE">
    <PROPRIETARY_NAME>RedEye Relief</PROPRIETARY_NAME>
    <NDC_PACKAGE_CODE>17312-058-15</NDC_PACKAGE_CODE>
    <STRENGTH>6[hp_X]/mL,6[hp_X]/mL,6[hp_X]/mL,6[hp_X]/mL,12[hp_X]/mL</STRENGTH>
	<DOSAGE_INFO type="LIQUID" form="NA" route="OPHTHALMIC"></DOSAGE_INFO>
    <LABELER_NAME>TRP Company</LABELER_NAME>
    <NON_PROPRIETARY_NAME>APIS MELLIFERA, EUPHRASIA STRICTA, CALCIUM SULFIDE, LOESELIA MEXICANA WHOLE, PULSATILLA VULGARIS</NON_PROPRIETARY_NAME>
    <SUBSTANCE_NAME>APIS MELLIFERA, EUPHRASIA STRICTA, CALCIUM SULFIDE, LOESELIA MEXICANA WHOLE, PULSATILLA VULGARIS</SUBSTANCE_NAME>
    <PRODUCT_TYPE_NAME type = "OTC"></PRODUCT_TYPE_NAME>
    <PACKAGE_DESC>1 TUBE in 1 PACKAGE (17312-167-13); 4 g in 1 TUBE</PACKAGE_DESC>
    <CERTIFIED_THROUGH>12/31/2019</CERTIFIED_THROUGH>
  </DRUG>
  <DRUG CATEGORY="REDEYE">
    <PROPRIETARY_NAME>RedEye Relief</PROPRIETARY_NAME>
    <NDC_PACKAGE_CODE>17312-058-15</NDC_PACKAGE_CODE>
    <STRENGTH>6[hp_X]/mL,6[hp_X]/mL,6[hp_X]/mL,6[hp_X]/mL,12[hp_X]/mL</STRENGTH>
	<DOSAGE_INFO type="LIQUID" form="NA" route="OPHTHALMIC"></DOSAGE_INFO>
    <LABELER_NAME>TRP Company</LABELER_NAME>
    <NON_PROPRIETARY_NAME>APIS MELLIFERA, EUPHRASIA STRICTA, CALCIUM SULFIDE, LOESELIA MEXICANA WHOLE, PULSATILLA VULGARIS</NON_PROPRIETARY_NAME>
    <SUBSTANCE_NAME>APIS MELLIFERA, EUPHRASIA STRICTA, CALCIUM SULFIDE, LOESELIA MEXICANA WHOLE, PULSATILLA VULGARIS</SUBSTANCE_NAME>
    <PRODUCT_TYPE_NAME type = "OTC"></PRODUCT_TYPE_NAME>
    <PACKAGE_DESC>1 TUBE in 1 PACKAGE (17312-167-13) ; 4 g in 1 TUBE</PACKAGE_DESC>
    <CERTIFIED_THROUGH>12/31/2019</CERTIFIED_THROUGH>
  </DRUG>
</ALL_DRUG_CODE>